---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: receiver
  name: receiver
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: receiver-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: receiver-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: receiver-role
subjects:
- kind: ServiceAccount
  name: receiver
  namespace: mock
